client_name          = "cliente-prueba"
environment          = "dev"
aws_account_id       = "239452641090"
oidc_role_name       = "GitHubTerraformAccessRole1"
bucket_name          = "terraform-state-cliente-prueba-dev"
dynamodb_table_name  = "terraform-locks-cliente-prueba"
